name: Build Saber Factory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'
    - name: Initialize modding environment
      uses: beat-forge/init-beatsaber@v1
    - name: Download Beatmods dependencies
      uses: Aeroluna/download-beatmods-deps@main
      with:
        project-path: '.'
    - name: Build
      id: Build
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.7.2-api
      run: dotnet build --configuration Release
    - name: Echo Filename
      run: echo "$BUILDTEXT ($ASSEMBLYNAME)"
      env:
        BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
        ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ./SaberFactory/bin/Release/Final
