name: Build Saber Factory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        game-version:
          - 1.39.1 
          - 1.42.0 # Currently pinning to this version because 1.42.1 isn't available yet, but shouldn't really break, because its just a minor version release
          - 1.40.8
    
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'
    - name: Initialize modding environment
      uses: beat-forge/init-beatsaber@v1
      with:
        version: ${{ matrix.game-version }}
    - name: Download Beatmods dependencies
      uses: Aeroluna/download-beatmods-deps@main
      with:
        project-path: 'SaberFactory/SaberFactory.csproj'
        path: './Refs'
        additional-sources: '["Aeroluna/Heck"]'
        game-version: ${{ matrix.game-version }}
        additional-dependencies: '{"Heck":"^1.8.2", "SiraUtil":"^3.2.1", "BeatSaberMarkupLanguage":"^1.12.5"}'
    - name: Build
      id: Build
      env:
        FrameworkPathOverride: /usr/lib/mono/4.7.2-api
      run: dotnet build --configuration Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SaberFactory-${{ matrix.game-version }}-${{ github.sha }}
        path: ./SaberFactory/bin/Release/Final