name: Release Saber Factory

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Initialize modding environment
        uses: beat-forge/init-beatsaber@v1
      - name: Download Beatmods dependencies
        uses: Aeroluna/download-beatmods-deps@main
        with:
          project-path: 'SaberFactory/SaberFactory.csproj'
          path: './Refs'
          game-version: 1.40.8
          additional-dependencies: '{}'
      - name: Build
        id: Build
        env:
          FrameworkPathOverride: /usr/lib/mono/4.7.2-api
        run: |
          dotnet build --configuration Release
          echo "filename=SaberFactory" >> "$GITHUB_OUTPUT"
      - name: Archive Release
        run: |
          cd SaberFactory/bin/Release/Final
          zip -r ../../../../${{ steps.Build.outputs.filename }}.zip .
      - name: Set tag output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Saber Factory ${{ steps.vars.outputs.tag }}
          artifacts: ${{ steps.Build.outputs.filename }}.zip
          bodyFile: changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          prerelease: true